// front-end/src/components/VenueCard.tsx
import {
  IonCard,
  IonCardContent,
  IonCardHeader,
  IonCardTitle,
  IonSkeletonText,
  IonImg,
  IonCardSubtitle,
  IonButton,
  IonIcon
} from '@ionic/react';
import { navigate } from 'ionicons/icons';

import { Venue } from 'models/venue';

import { mdParser, openGeoLocationInMap } from '../utils';
import { getImageURLByURI, venuesFallbackImageURL } from '../utils/data';

interface ContainerProps {
  venue?: Venue;
}

const VenueCard: React.FC<ContainerProps> = ({ venue }) => {
  return venue ? (
    <IonCard color="white">
      <IonImg
        src={getImageURLByURI(venue.imageURI)}
        onIonError={(e: any) => (e.target.src = venuesFallbackImageURL)}
      ></IonImg>
      <IonCardHeader>
        <IonCardTitle>{venue.name}</IonCardTitle>
        <IonCardSubtitle>{venue.address}</IonCardSubtitle>
      </IonCardHeader>
      <IonCardContent>
        {venue.address ? (
          <div className="ion-text-right" style={{ marginBottom: 30 }}>
            <IonButton onClick={() => openGeoLocationInMap(venue.latitude, venue.longitude)}>
              Navigate to the venue <IonIcon icon={navigate} slot="end"></IonIcon>
            </IonButton>
          </div>
        ) : (
          ''
        )}
        <div className="divDescription">
          {venue.description ? (
            <span dangerouslySetInnerHTML={{ __html: mdParser.render(venue.description) }}></span>
          ) : (
            ''
          )}
        </div>
      </IonCardContent>
    </IonCard>
  ) : (
    <IonCard color="white">
      <IonSkeletonText animated style={{ height: 200 }} />
      <IonCardHeader>
        <IonCardTitle>
          <IonSkeletonText animated style={{ width: '60%' }} />
        </IonCardTitle>
      </IonCardHeader>
      <IonCardContent>
        <IonSkeletonText animated style={{ width: '80%' }} />
        <IonSkeletonText animated style={{ width: '70%' }} />
        <IonSkeletonText animated style={{ width: '60%' }} />
      </IonCardContent>
    </IonCard>
  );
};

export default VenueCard;

// front-end/src/app/tabs/venues/venueCard.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';
import { FormsModule } from '@angular/forms';
import {
  IonCard,
  IonCardContent,
  IonCardHeader,
  IonCardSubtitle,
  IonCardTitle,
  IonImg,
  IonSkeletonText
} from '@ionic/angular/standalone';

import { HTMLEditorComponent } from 'src/app/common/htmlEditor.component';

import { AppService } from 'src/app/app.service';

import { Venue } from '@models/venue.model';

@Component({
  standalone: true,
  imports: [
    // Angular
    CommonModule,
    FormsModule,
    // App
    HTMLEditorComponent,
    // Ionic
    IonCard,
    IonCardContent,
    IonCardHeader,
    IonCardSubtitle,
    IonCardTitle,
    IonImg,
    IonSkeletonText
  ],
  selector: 'app-venue-card',
  template: `
    <ion-card *ngIf="venue" color="white">
      <ion-img [src]="app.getImageURLByURI(venue.imageURI)"></ion-img>
      <ion-card-header>
        <ion-card-title>{{ venue.name }}</ion-card-title>
        <ion-card-subtitle>{{ venue.address }}</ion-card-subtitle>
      </ion-card-header>
      <ion-card-content>
        <!-- @todo add map #61 -->
        <!-- <div *ngIf="venue.address" class="ion-text-right" style="margin-bottom: 30px;">
          <ion-button (click)="openMap(venue.latitude, venue.longitude)">
            Navigate to the venue
            <ion-icon slot="end" name="navigate"></ion-icon>
          </ion-button>
        </div> -->
        <app-html-editor [content]="venue.description" [editMode]="false"></app-html-editor>
      </ion-card-content>
    </ion-card>

    <ion-card *ngIf="!venue" color="white">
      <ion-skeleton-text animated style="height: 200px;"></ion-skeleton-text>
      <ion-card-header>
        <ion-card-title>
          <ion-skeleton-text animated style="width: 60%;"></ion-skeleton-text>
        </ion-card-title>
        <ion-card-subtitle>
          <ion-skeleton-text animated style="width: 50%;"></ion-skeleton-text>
        </ion-card-subtitle>
      </ion-card-header>
      <ion-card-content>
        <ion-skeleton-text animated style="width: 80%;"></ion-skeleton-text>
        <ion-skeleton-text animated style="width: 70%;"></ion-skeleton-text>
        <ion-skeleton-text animated style="width: 60%;"></ion-skeleton-text>
      </ion-card-content>
    </ion-card>
  `
})
export class VenueCardStandaloneComponent {
  @Input() venue: Venue;

  constructor(public app: AppService) {}

  openMap(latitude: number, longitude: number): void {
    return; // @todo add map #61
    // openGeoLocationInMap(latitude, longitude);
  }
}
