// front-end/src/components/SpeakerCard.tsx
import { useHistory } from 'react-router';
import {
  IonLabel,
  IonCard,
  IonCardContent,
  IonCardHeader,
  IonCardTitle,
  IonSkeletonText,
  IonRow,
  IonCol,
  IonAvatar,
  IonImg,
  IonCardSubtitle,
  IonButton,
  IonIcon
} from '@ionic/react';
import { eye, mail } from 'ionicons/icons';

import { Speaker } from 'models/speaker';

import { mdParser } from '../utils';
import { getImageURLByURI, usersFallbackImageURL } from '../utils/data';

interface ContainerProps {
  speaker?: Speaker;
  preview?: boolean;
  select?: () => void;
}

const SpeakerCard: React.FC<ContainerProps> = ({ speaker, preview, select }) => {
  const history = useHistory();

  return speaker ? (
    <IonCard
      button={!!select}
      onClick={select}
      color="white"
      style={{ height: preview ? '100%' : 'auto', width: '100%' }}
    >
      <IonCardHeader>
        <IonRow className="ion-align-items-center">
          <IonCol size="12" sizeSm={preview ? '12' : '3'}>
            <IonAvatar style={avatarStyle}>
              <IonImg
                src={getImageURLByURI(speaker.imageURI)}
                onIonError={(e: any) => (e.target.src = usersFallbackImageURL)}
              ></IonImg>
            </IonAvatar>
          </IonCol>
          <IonCol size="12" sizeSm={preview ? '12' : '9'}>
            <IonCardTitle style={preview ? { marginTop: 8 } : undefined}>
              <h2 style={{ marginTop: 3, marginBottom: 6 }} className={preview ? 'ion-text-center' : ''}>
                {speaker.name}
              </h2>
            </IonCardTitle>
            <IonCardSubtitle className={preview ? 'ion-text-center' : ''}>{speaker.organization.name}</IonCardSubtitle>
            <IonCardSubtitle className={preview ? 'ion-text-center' : ''} style={{ fontWeight: 300 }}>
              {speaker.title}
            </IonCardSubtitle>
          </IonCol>
        </IonRow>
      </IonCardHeader>
      {preview ? (
        ''
      ) : (
        <IonCardContent>
          <div className="ion-text-right" style={{ marginBottom: 10 }}>
            <IonButton
              fill="clear"
              color="dark"
              onClick={() => history.push('/organization/' + speaker.organization.organizationId)}
            >
              Discover organization <IonIcon icon={eye} slot="end"></IonIcon>
            </IonButton>
            {speaker.contactEmail ? (
              <IonButton target="_blank" href={`mailto:${speaker.contactEmail}?subject=EGM%20contact%20request`}>
                Contact me <IonIcon icon={mail} slot="end"></IonIcon>
              </IonButton>
            ) : (
              ''
            )}
          </div>

          <div className="divDescription">
            {speaker.description ? (
              <span dangerouslySetInnerHTML={{ __html: mdParser.render(speaker.description) }}></span>
            ) : (
              ''
            )}
          </div>
        </IonCardContent>
      )}
    </IonCard>
  ) : (
    <IonCard color="white">
      <IonCardHeader>
        <IonRow>
          <IonCol size="12" sizeSm={preview ? '12' : '3'}>
            <IonAvatar style={avatarStyle}>
              <IonSkeletonText animated />
            </IonAvatar>
          </IonCol>
          <IonCol size="12" sizeSm={preview ? '12' : '9'}>
            <IonCardSubtitle>
              <IonSkeletonText animated style={{ width: '40%' }} />
            </IonCardSubtitle>
            <IonCardTitle>
              <IonSkeletonText animated style={{ width: '60%' }} />
            </IonCardTitle>
          </IonCol>
        </IonRow>
        <IonCardTitle>
          <IonLabel></IonLabel>
        </IonCardTitle>
      </IonCardHeader>
      <IonCardContent>
        <IonSkeletonText animated style={{ width: '80%' }} />
        <IonSkeletonText animated style={{ width: '70%' }} />
        <IonSkeletonText animated style={{ width: '60%' }} />
      </IonCardContent>
    </IonCard>
  );
};

export default SpeakerCard;

const avatarStyle = { margin: '0 auto', width: 100, height: 100 };

// front-end/src/app/tabs/speakers/speakerCard.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';
import { FormsModule } from '@angular/forms';
import {
  IonButton,
  IonCard,
  IonCardContent,
  IonCardHeader,
  IonCardSubtitle,
  IonCardTitle,
  IonIcon,
  IonImg,
  IonInput,
  IonItem,
  IonList,
  IonSkeletonText
} from '@ionic/angular/standalone';

import { HTMLEditorComponent } from 'src/app/common/htmlEditor.component';

import { AppService } from 'src/app/app.service';

import { Speaker } from '@models/speaker.model';

@Component({
  standalone: true,
  imports: [
    // Angular
    CommonModule,
    FormsModule,
    // App
    HTMLEditorComponent,
    // Ionic
    IonButton,
    IonCard,
    IonCardContent,
    IonCardHeader,
    IonCardSubtitle,
    IonCardTitle,
    IonIcon,
    IonImg,
    IonInput,
    IonItem,
    IonList,
    IonSkeletonText
  ],
  selector: 'app-speaker-card',
  template: `
    <ng-container *ngIf="speaker; else skeletonTemplate">
      <ion-card *ngIf="preview" [color]="preview ? 'white' : ''">
        <ion-card-header>
          <ion-card-title>{{ speaker.name }}</ion-card-title>
          <ion-card-subtitle>{{ speaker.organization.name }}</ion-card-subtitle>
        </ion-card-header>
      </ion-card>

      <ion-card *ngIf="!preview" color="white">
        <ion-card-header>
          <ion-card-subtitle class="ion-text-right">
            <ion-img [src]="app.getImageURLByURI(speaker.imageURI)"></ion-img>
          </ion-card-subtitle>
          <ion-card-title>{{ speaker.name }}</ion-card-title>
          <ion-card-subtitle>
            <ion-button
              fill="clear"
              color="dark"
              (click)="app.goToInTabs(['organizations', speaker.organization.organizationId])"
            >
              {{ speaker.organization.name }}
            </ion-button>
          </ion-card-subtitle>
          <ion-card-subtitle>
            <a [href]="'mailto:' + speaker.contactEmail">{{ speaker.contactEmail }}</a>
          </ion-card-subtitle>
        </ion-card-header>
        <ion-card-content>
          <ion-list>
            <ion-item *ngIf="speaker.socialMedia.linkedIn">
              <ion-icon name="logo-linkedin" slot="start"/>
              <ion-input [(ngModel)]="speaker.socialMedia.linkedIn"></ion-input>
            </ion-item>
            <ion-item *ngIf="speaker.socialMedia.instagram">
              <ion-icon name="logo-instagram" slot="start"/>
              <ion-input [(ngModel)]="speaker.socialMedia.instagram"></ion-input>
            </ion-item>
            <ion-item *ngIf="speaker.socialMedia.twitter">
              <ion-icon name="logo-twitter" slot="start"/>
              <ion-input [(ngModel)]="speaker.socialMedia.twitter"></ion-input>
            </ion-item>
            <app-html-editor [content]="speaker.description" [editMode]="false"></app-html-editor>
          </ion-list>
        </ion-card-content>
      </ion-card>
    </ng-container>

    <ng-template #skeletonTemplate>
      <ion-card color="white">
        <ion-skeleton-text animated style="height: 200px;"></ion-skeleton-text>
        <ion-card-header>
          <ion-card-title>
            <ion-skeleton-text animated style="width: 60%;"></ion-skeleton-text>
          </ion-card-title>
          <ion-card-subtitle>
            <ion-skeleton-text animated style="width: 50%;"></ion-skeleton-text>
          </ion-card-subtitle>
        </ion-card-header>
        <ion-card-content>
          <ion-skeleton-text animated style="width: 80%;"></ion-skeleton-text>
          <ion-skeleton-text animated style="width: 70%;"></ion-skeleton-text>
          <ion-skeleton-text animated style="width: 60%;"></ion-skeleton-text>
        </ion-card-content>
      </ion-card>
    </ng-template>
  `
})
export class SpeakerCardStandaloneComponent {
  @Input() speaker: Speaker;
  @Input() preview: boolean;

  constructor(public app: AppService) {}
}
