// front-end/src/app/tabs/organizations/organizationCard.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';
import { FormsModule } from '@angular/forms';
import {
  IonCard,
  IonCardContent,
  IonCardHeader,
  IonCardSubtitle,
  IonCardTitle,
  IonImg,
  IonSkeletonText
} from '@ionic/angular/standalone';

import { HTMLEditorComponent } from 'src/app/common/htmlEditor.component';

import { AppService } from 'src/app/app.service';

import { Organization } from '@models/organization.model';

@Component({
  standalone: true,
  imports: [
    // Angular
    CommonModule,
    FormsModule,
    // App
    HTMLEditorComponent,
    // Ionic
    IonCard,
    IonCardContent,
    IonCardHeader,
    IonCardSubtitle,
    IonCardTitle,
    IonImg,
    IonSkeletonText
  ],
  selector: 'app-organization-card',
  template: `
    <ion-card *ngIf="organization" color="white">
      <ion-img [src]="app.getImageURLByURI(organization.imageURI)"></ion-img>
      <ion-card-header>
        <ion-card-title>{{ organization.name }}</ion-card-title>
        <ion-card-subtitle>
          <a *ngIf="organization.website" [href]="(organization.website.startsWith('http') ? '' : 'http://') + organization.website" target="_blank">{{ organization.website }}</a>
        </ion-card-subtitle>
        <ion-card-subtitle>
          <a [href]="'mailto:' + organization.contactEmail">{{ organization.contactEmail }}</a>
        </ion-card-subtitle>
      </ion-card-header>
      <ion-card-content>
      <app-html-editor [content]="organization.description" [editMode]="false"></app-html-editor>
      </ion-card-content>
    </ion-card>

    <ion-card *ngIf="!organization" color="white">
      <ion-skeleton-text animated style="height: 200px;"></ion-skeleton-text>
      <ion-card-header>
        <ion-card-title>
          <ion-skeleton-text animated style="width: 60%;"></ion-skeleton-text>
        </ion-card-title>
        <ion-card-subtitle>
          <ion-skeleton-text animated style="width: 50%;"></ion-skeleton-text>
        </ion-card-subtitle>
      </ion-card-header>
      <ion-card-content>
        <ion-skeleton-text animated style="width: 80%;"></ion-skeleton-text>
        <ion-skeleton-text animated style="width: 70%;"></ion-skeleton-text>
        <ion-skeleton-text animated style="width: 60%;"></ion-skeleton-text>
      </ion-card-content>
    </ion-card>
  `
})
export class OrganizationCardStandaloneComponent {
  @Input() organization: Organization;
  @Input() preview: boolean;

  constructor(public app: AppService) {}
}

// front-end/src/components/OrganizationCard.tsx
import {
  IonLabel,
  IonCard,
  IonCardContent,
  IonCardHeader,
  IonCardTitle,
  IonSkeletonText,
  IonImg,
  IonItem,
  IonTitle
} from '@ionic/react';

import { Organization } from 'models/organization';
import { getImageURLByURI, organizationsFallbackImageURL } from '../utils/data';

interface ContainerProps {
  organization?: Organization;
  preview?: boolean;
  select?: () => void;
}

const OrganizationCard: React.FC<ContainerProps> = ({ organization, preview, select }) => {
  return organization ? (
    <IonCard button={!!select} onClick={select} color="white" style={{ height: preview ? '120px' : 'auto' }}>
      <IonCardHeader>
        {organization.imageURI ? (
          <IonImg
            src={getImageURLByURI(organization.imageURI)}
            onIonError={(e: any) => (e.target.src = organizationsFallbackImageURL)}
            style={{ margin: '0 auto', maxWidth: preview ? 150 : 250, height: preview ? 90 : 'auto' }}
          ></IonImg>
        ) : (
          <IonTitle>
            <h2 className="ion-text-center">{organization.name}</h2>
          </IonTitle>
        )}
      </IonCardHeader>
      {preview ? (
        ''
      ) : (
        <IonCardContent>
          <>
            {organization.imageURI ? (
              <IonItem color="white" lines="none">
                <IonLabel className="ion-text-center">
                  <b>{organization.name}</b>
                </IonLabel>
              </IonItem>
            ) : (
              ''
            )}
            <IonItem color="light" lines="none">
              <IonLabel className="ion-text-wrap">{organization.description}</IonLabel>
            </IonItem>
          </>
        </IonCardContent>
      )}
    </IonCard>
  ) : (
    <IonCard color="white">
      <IonCardHeader>
        <IonCardTitle>
          <IonSkeletonText animated style={{ height: 90 }} />
        </IonCardTitle>
      </IonCardHeader>
      {preview ? (
        ''
      ) : (
        <IonCardContent>
          <IonSkeletonText animated style={{ width: '80%' }} />
          <IonSkeletonText animated style={{ width: '70%' }} />
          <IonSkeletonText animated style={{ width: '60%' }} />
        </IonCardContent>
      )}
    </IonCard>
  );
};

export default OrganizationCard;
