// front-end/src/app/tabs/rooms/roomCard.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';
import { FormsModule } from '@angular/forms';
import {
  IonButton,
  IonCard,
  IonCardContent,
  IonCardHeader,
  IonCardSubtitle,
  IonCardTitle,
  IonIcon,
  IonImg,
  IonLabel,
  IonSkeletonText
} from '@ionic/angular/standalone';

import { HTMLEditorComponent } from 'src/app/common/htmlEditor.component';

import { AppService } from 'src/app/app.service';

import { Room } from '@models/room.model';

@Component({
  standalone: true,
  imports: [
    // Angular
    CommonModule,
    FormsModule,
    // App
    HTMLEditorComponent,
    // Ionic
    IonButton,
    IonCard,
    IonCardContent,
    IonCardHeader,
    IonCardSubtitle,
    IonCardTitle,
    IonIcon,
    IonImg,
    IonLabel,
    IonSkeletonText
  ],
  selector: 'app-room-card',
  template: `
    <ng-container *ngIf="room; else skeletonTemplate">
      <ion-card *ngIf="preview" [color]="preview ? 'white' : ''">
        <ion-card-header>
          <ion-card-title>{{ room.name }}</ion-card-title>
          <ion-card-subtitle>{{ room.internalLocation }}</ion-card-subtitle>
        </ion-card-header>
      </ion-card>

      <ion-card *ngIf="!preview" color="white">
        <ion-img [src]="app.getImageURLByURI(room.imageURI)"></ion-img>
        <ion-card-header>
          <ion-card-subtitle style="font-weight: 300;" class="ion-text-right">
            <ion-button fill="clear" (click)="app.goToInTabs(['venues', room.venue.venueId])">
              <ion-icon name="location-outline"></ion-icon>
              <ion-label>
                {{ room.venue.name }}
              </ion-label>
            </ion-button>
          </ion-card-subtitle>
          <ion-card-title>{{ room.name }}</ion-card-title>
          <ion-card-subtitle>{{ room.internalLocation }}</ion-card-subtitle>
        </ion-card-header>
        <ion-card-content>
        <app-html-editor [content]="room.description" [editMode]="false"></app-html-editor>
        </ion-card-content>
      </ion-card>
    </ng-container>

    <ng-template #skeletonTemplate>
      <ion-card color="white">
        <ion-skeleton-text animated style="height: 200px;"></ion-skeleton-text>
        <ion-card-header>
          <ion-card-title>
            <ion-skeleton-text animated style="width: 60%;"></ion-skeleton-text>
          </ion-card-title>
          <ion-card-subtitle>
            <ion-skeleton-text animated style="width: 50%;"></ion-skeleton-text>
          </ion-card-subtitle>
        </ion-card-header>
        <ion-card-content>
          <ion-skeleton-text animated style="width: 80%;"></ion-skeleton-text>
          <ion-skeleton-text animated style="width: 70%;"></ion-skeleton-text>
          <ion-skeleton-text animated style="width: 60%;"></ion-skeleton-text>
        </ion-card-content>
      </ion-card>
    </ng-template>
  `
})
export class RoomCardStandaloneComponent {
  @Input() room: Room;
  @Input() preview: boolean;

  constructor(public app: AppService) {}
}

// front-end/src/components/RoomCard.tsx
import { Link } from 'react-router-dom';
import {
  IonCard,
  IonCardContent,
  IonCardHeader,
  IonCardTitle,
  IonSkeletonText,
  IonImg,
  IonCardSubtitle,
  IonItem,
  IonLabel,
  IonIcon
} from '@ionic/react';
import { locationOutline } from 'ionicons/icons';

import { Room } from 'models/room';

import { mdParser } from '../utils';
import { getImageURLByURI, venuesFallbackImageURL } from '../utils/data';

interface ContainerProps {
  room?: Room;
  preview?: boolean;
  select?: () => void;
}

const RoomCard: React.FC<ContainerProps> = ({ room, preview, select }) => {
  return room ? (
    preview ? (
      <IonItem button={!!select} onClick={select}>
        <IonLabel>
          {room.name}
          <p>{room.internalLocation}</p>
        </IonLabel>
      </IonItem>
    ) : (
      <IonCard color="white">
        <IonImg
          src={getImageURLByURI(room.imageURI)}
          onIonError={(e: any) => (e.target.src = venuesFallbackImageURL)}
        ></IonImg>
        <IonCardHeader>
          <IonCardSubtitle style={{ fontWeight: 300 }} className="ion-text-right">
            <Link to={'/venue/' + room.venue.venueId}>
              <IonIcon icon={locationOutline}></IonIcon> {room.venue.name}
            </Link>
          </IonCardSubtitle>
          <IonCardTitle>{room.name}</IonCardTitle>
          <IonCardSubtitle>{room.internalLocation}</IonCardSubtitle>
        </IonCardHeader>
        <IonCardContent>
          <div className="divDescription">
            {room.description ? (
              <span dangerouslySetInnerHTML={{ __html: mdParser.render(room.description) }}></span>
            ) : (
              ''
            )}
          </div>
        </IonCardContent>
      </IonCard>
    )
  ) : (
    <IonCard color="white">
      <IonSkeletonText animated style={{ height: 200 }} />
      <IonCardHeader>
        <IonCardTitle>
          <IonSkeletonText animated style={{ width: '60%' }} />
        </IonCardTitle>
        <IonCardSubtitle>
          <IonSkeletonText animated style={{ width: '50%' }} />
        </IonCardSubtitle>
      </IonCardHeader>
      <IonCardContent>
        <IonSkeletonText animated style={{ width: '80%' }} />
        <IonSkeletonText animated style={{ width: '70%' }} />
        <IonSkeletonText animated style={{ width: '60%' }} />
      </IonCardContent>
    </IonCard>
  );
};

export default RoomCard;
